### ISSUE TITLE
Remove require calls and use the roxygen2 importFrom paradigm instead.

### ISSUE THREAD

**Issue by zkamvar** [grunwaldlab/quiltr#1]
Looking through your package, I have noticed such lines as [here](https://github.com/zachary-foster/labtools/blob/c8d6233254ab49aec2ac2cd255aa0c41523b5e20/R/parsers.R#L9-L11) where the function calls require on a package needed and if the package isn't available, the function is halted and the message to the user is to install that package. Several of these would result in frustration of end users that would not know all the packages required for this package to run. 

A better paradigm would be to [use roxygen2's @importFrom roxygen comment](http://cran.r-project.org/web/packages/roxygen2/vignettes/namespace.html). This has a few advantages over the require paradigm:
1. It makes clear which functions are from which package
2. It makes clear which packages are required for the user to have before your package can function
3. devtools' `install_github` function will automatically download packages that are required for your package to run.

So, before the function call, place the roxygen comment like so.

``` s
#' @importFrom package1 thisFunk thatFunk
#' @importFrom package2 anotherFunk
```

**Comment by zachary-foster** [comment]
Thanks zkamvar! I made the changes you suggested.
