### ISSUE TITLE
New notebooks to be written on current path without the absolute path

### ISSUE THREAD

**Issue by Tabima** [grunwaldlab/quiltr#31]
So far, just encountered a simple problem:
When creating a new notebook in a folder I created particularly for the entire analysis (`mtdna/`:

``` r
>library(labtools)
>new_notebook(".",name = "Mira_MITObim",open=T)
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file './2015_05_05-Mira_MITObim/info.yaml': No such file or directory
```

I assumed it was because I was using the realtive path for the current directory `(".")`. I decided to add the full path: 

``` r
> getwd()
[1] "/home/likewise-open/USDA-ARS/javier.tabima/Desktop/rubi_genomes/mt_dna"
> new_notebook( "/home/likewise-open/USDA-ARS/javier.tabima/Desktop/rubi_genomes/mt_dna",name = "Mira_MITObim",open=T)
Initialized empty Git repository in /home/likewise-open/USDA-ARS/javier.tabima/Desktop/rubi_genomes/mt_dna/2015_05_05-Mira_MITObim/.git/
```

It  **<span style="color:green">WORKS!</span>**! 

Its simple enough to us to understand that this is an issue of abolute vs. relative paths, but what about the naive user? Is there any way that it could work only with the `location="."` option?

Thanks!

**Comment by zachary-foster** [comment]
Thanks for reporting the bug @Tabima ! I fixed it and it works for me now with relative paths.

**Comment by Tabima** [comment]
Awesome! it works!!
<3
