### ISSUE TITLE
Devel branch?

### ISSUE THREAD

**Issue by knausb** [grunwaldlab/quiltr#33]
Now that you're asking others to try your package it may be prudent to create a new branch.  This maintains a stable branch for others to try while providing a branch for you to continue to make changes to without worrying about how it may affect other users.

**Comment by grunwald** [comment]
Zach has his own branch. He still needs to wrap it into a package for loading and testing?

**Comment by zachary-foster** [comment]
I agree. There should be a devel branch. I will start one next time I add or make a change to functionality and merge it into the master branch whenever there is a minor version number increase. 

@grunwald, Im not sure I understand your comment. Currently there is only the `master` branch, which is the one people will be installing by default. Having a devel branch will allow for me to make commits that could potentially break something or introduce incomplete functionality without someone installing a version of the package in that state. Whenever the changes made are stable, I will merge the devel branch back into `master`, making the changes available to users.  Sound good?

**Comment by zachary-foster** [comment]
I started the `devel` branch, so I am closeing this issue.
