### ISSUE TITLE
Add instructions for download of package, install and first use

### ISSUE THREAD

**Issue by grunwald** [grunwaldlab/quiltr#34]
We need a few lines of instructions on how to install and get started with package.

**Comment by grunwald** [comment]
Just noticed that the download and install is there. Just need to add instructions for each of the main functions.

**Comment by zachary-foster** [comment]
Ok, the basics should be there. There are other functions involved with creating things like PCR and nanodrop recepies, but these are not essential to using the package for making a notebook.
