### ISSUE TITLE
Abstract website build function so that it can use arbitrary directory structures

### ISSUE THREAD

**Issue by zachary-foster** [grunwaldlab/quiltr#47]
Currently, users must follow the directory structure of Noble 2009 for the website to be built. 
This is not ideal for all users and purposes. Instead, there should be a set of flexible options to specify where .html files in any location are displayed on the website. I can think of three sources of information to determine website display location:
- Directory path from some common point, possibly with directory names split by a `sep` option
- File names, possibly split by a `sep` option
- A `.notebook` file specifing where individual notes go

**Comment by grunwald** [comment]
Might be nice to specify a couple of sets of folders (wet-lab, bioinformatics, etc.) as well as a custom set of folders.

**Comment by zachary-foster** [comment]
@grunwald, good idea! Abstracting the website building function should allow for making various templates for notebooks easy since they can all use the same function with different options and template directory structures. I will start a new issue for this (issue #49).

**Comment by zachary-foster** [comment]
This is done
